apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ include "argo_test.fullname" . }}-migrator-
  labels:
    {{- include "argo_test.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: migrator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: 
          - python
          - -m
          - argo_testing
          - migrate
        {{- with .Values.env }}
        env:
        {{- range $key, $val := . }}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        {{- end }}
      restartPolicy: Never
